spring:
  datasource:
    url: jdbc:mysql://localhost:3306/iFilm
    username: admin
    password: abc@123
    driverClassName: com.mysql.jdbc.Driver
    hibernate-dialect: org.hibernate.dialect.MySQL5Dialect
  jpa:
    hibernate:
      ddl-auto: update